### ISSUE TITLE
Tiling Sprite Sheet

### ISSUE THREAD

**Issue by tusing** [tusing/hpffcss#1]
## The sprite sheet seems to tile over the entire comment area as a clickable link, making usage impossible.
- [Go to /r/hpfanficcsstest](https://www.reddit.com/r/hpfanficcsstest/comments/3nqeqt/this_is_a_post/) and click on the "RELATED", you should see the error.
- [Some users seem to be getting it in the comments, too.](https://i.imgur.com/ywVoxnr.jpg)

**Comment by babelfish** [comment]
I think the styling was fucked up on thumbnails and in the reddit preferences there's an option to display thumbnails regardless of the subreddit setting.
