### ISSUE TITLE
Footer Hidden by Tiling Background

### ISSUE THREAD

**Issue by tusing** [tusing/hpffcss#2]
The footer with all the Reddit "About" links is hidden by the tiling background; try going to the bottom of [/r/hpfanficcsstest](https://www.reddit.com/r/hpfanficcsstest/) to try it out yourself.

**Comment by babelfish** [comment]
I have a fix for this after my PR to dedupe the stylesheet is merged.

**Comment by tusing** [comment]
Thanks! I believe I made you aa contributor because of my hectic schedule this week. Thank you for the changes so far! You should be able to push and pull without issue now.
